name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Upload files to S3
        run: aws s3 sync ./ s3://your-bucket-name/ --exclude ".git/*"  # Replace with your bucket name

      - name: Send SSM Command to Deploy
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-0123456789abcdef0" \  # Replace with your EC2 instance ID
            --parameters 'commands=["aws s3 sync s3://your-bucket-name/ /home/ec2-user/app", "cd /home/ec2-user/app", "npm install", "npm run start"]'


