name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Sync files to EC2
        run: |
          aws s3 cp --recursive ./ s3://your-bucket-name/ --exclude ".git/*"
          aws ec2-instance-connect send-ssh-public-key \
            --region us-east-1 \
            --instance-id i-0123456789abcdef0 \
            --availability-zone us-east-1a \
            --instance-os-user ec2-user \
            --ssh-public-key file://~/.ssh/id_rsa.pub
          ssh -i ~/.ssh/id_rsa ec2-user@your-ec2-public-dns 'aws s3 sync s3://your-bucket-name/ /home/ec2-user/app'

      - name: Install dependencies and start Medusa
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@your-ec2-public-dns << 'EOF'
            cd /home/ec2-user/app
            npm install
            npm run start
          EOF

