name: Deploy Medusa Application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: medusa-app
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy Docker image to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Log in to Amazon ECR
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            
            # Pull the latest Docker image from ECR
            docker pull ${{ secrets.ECR_REGISTRY }}/medusa-app:${{ github.sha }}
            
            # Stop and remove existing container if it exists
            docker stop medusa-container || true
            docker rm medusa-container || true
            
            # Run the new Docker container
            docker run -d --name medusa-container -p 80:80 ${{ secrets.ECR_REGISTRY }}/medusa-app:${{ github.sha }}
